import io
import re

from textwrap import dedent

from tola.assembly.parser import parse_agp

def	test_parse_agp():

    # Careful using auto-formatters on this code which may strip tab
    # characters from this test AGP
    agp = strip_leading_spaces(
        """
        ##agp-version 2.1
        #
        # DESCRIPTION: Generated by PretextView Version 0.2.5
        # HiC MAP RESOLUTION: 8666.611572 bp/texel

        Scaffold_1	1	21337197	1	W	scaffold_1	1	21337197	+	Painted
        Scaffold_1	21337198	21337297	2	U	100	scaffold	yes	proximity_ligation
        Scaffold_1	21337298	21917959	3	W	scaffold_21	1	580662	+
        Scaffold_1	21917960	21918059	4	U	100	scaffold	yes	proximity_ligation
        Scaffold_1	21918060	24379376	5	W	scaffold_1	21770529	24231845	-	Painted
        Scaffold_2	1	3206646	1	W	scaffold_2	1	3206646	+	Painted
        Scaffold_2	3206647	3206746	2	U	100	scaffold	yes	proximity_ligation
        Scaffold_2	3206747	3267412	3	W	scaffold_67	1	60666	+	Painted
        Scaffold_2	3267413	3267512	4	U	100	scaffold	yes	proximity_ligation
        Scaffold_2	3267513	28348686	5	W	scaffold_2	3206647	28287820	+	Painted
        """
    )

    fh = io.StringIO(agp)
    a1 = parse_agp(fh, "aaBbbCccc1")
    assert str(a1) == strip_leading_spaces(
        """
        Assembly: aaBbbCccc1
          # DESCRIPTION: Generated by PretextView Version 0.2.5
          # HiC MAP RESOLUTION: 8666.611572 bp/texel
          Scaffold_1
                      1    21337197  scaffold_1:1-21337197(+) Painted
               21337198    21337297  Gap:100 scaffold
               21337298    21917959  scaffold_21:1-580662(+)
               21917960    21918059  Gap:100 scaffold
               21918060    24379376  scaffold_1:21770529-24231845(-) Painted
          Scaffold_2
                      1     3206646  scaffold_2:1-3206646(+) Painted
                3206647     3206746  Gap:100 scaffold
                3206747     3267412  scaffold_67:1-60666(+) Painted
                3267413     3267512  Gap:100 scaffold
                3267513    28348686  scaffold_2:3206647-28287820(+) Painted
        """
    )

def strip_leading_spaces(txt):
    return dedent(txt).lstrip("\n")

def	test_parse_tpf():
    pass

if	__name__ == '__main__':
    test_parse_agp()
    test_parse_tpf()
