"""
A collection of functions for writing output files.
"""

import logging
import re
import sys
from pathlib import Path
from typing import IO, Any

import click
import yaml
from zlib_ng import gzip_ng_threaded

from tola.assembly.assembly import Assembly
from tola.assembly.assembly_set import AssemblySet
from tola.assembly.assembly_stats import AssemblyStats
from tola.assembly.format import format_agp, format_tpf
from tola.assembly.gfa_stats import GfaStats, VgpStats
from tola.assembly.sanger_files import AssemblyYaml
from tola.fasta.stream import FastaCollection, FastaStream

log = logging.getLogger(__name__)


def get_output_filehandle(path: Path, clobber: bool, mode: str = "") -> IO[Any]:
    """
    Creates an output filehandle, which may be gzip-compressed.  Will fail if
    the destination file exists and `clobber != True`.  Prints the names of
    files written to STDERR.
    """
    op = "Overwrote" if path.exists() else "Created"

    # Must choose binary output mode if output is gzip compressed
    gz = path.suffix == ".gz"
    if gz:
        mode = "b"
    mode = "w" + mode if clobber else "x" + mode

    try:
        out_fh = (
            gzip_ng_threaded.open(path, mode, compresslevel=6, threads=2)
            if gz
            else path.open(mode)
        )
    except FileExistsError:
        log.error(f"Output file '{path}' already exists")
        sys.exit(1)
    click.echo(f"{op:>11}: '{path}'", err=True)
    return out_fh


def write_assemblies(
    fai_coll: FastaCollection | None,
    out_fmt: str,
    out_dir: Path,
    suffix: str,
    out_assemblies: AssemblySet,
    clobber: bool,
) -> dict[str | None, tuple[Assembly, Path]]:
    """
    Writes each assembly in the collection their requested destinations.
    """
    asm_files_written = {}
    for asm_key, asm in out_assemblies.items():
        output_file = out_dir / f"{asm.name}{suffix}"
        write_assembly(fai_coll, asm, output_file, out_fmt, clobber)
        if asm.curated:
            asm_files_written[asm_key] = (asm, output_file)
    return asm_files_written


def write_assembly(
    fai_coll: FastaCollection | None,
    out_asm: Assembly,
    output_file: Path | None,
    out_fmt: str | None,
    clobber: bool,
):
    """
    Writes an assembly to TPF, AGP or (optionally gzip-compressed) FASTA, or
    in the `Assembly`'s string representation when writing to STDOUT.
    """
    if output_file:
        mode = "b" if out_fmt == "FASTA" else ""
        out_fh = get_output_filehandle(output_file, clobber, mode)
    else:
        out_fmt = "STR"
        out_fh = sys.stdout

    if out_fmt == "TPF":
        format_tpf(out_asm, out_fh)
    elif out_fmt == "AGP":
        format_agp(out_asm, out_fh)
    elif out_fmt == "FASTA":
        if fai_coll is None:
            log.error("Cannot write FASTA output file without FASTA input!")
            sys.exit(1)
        stream = FastaStream(out_fh, fai_coll)
        stream.write_assembly(out_asm)

        # Save a .agp file alongside the .fa / .fasta
        output_agp = output_file.with_suffix(".agp")  # ty: ignore[unresolved-attribute]
        agp_fh = get_output_filehandle(output_agp, clobber)
        format_agp(out_asm, agp_fh)

    elif out_fmt == "STR":
        out_fh.write("\n")
        out_fh.write(str(out_asm))


def write_assembly_stats(
    draft_yaml: AssemblyYaml,
    asm_files: dict[str | None, tuple[Assembly, Path]],
    clobber: bool,
):
    """
    Writes `.gfastats` and `.gather_vgp_stats` files, which are both uploaded
    to the assembly's JIRA ticket.  They are generated by running `gfastats`.
    """
    for name, asm_path in asm_files.items():
        asm, asm_file = asm_path

        if source_hap := asm.source_haplotype:
            name = source_hap.lower()
        else:
            name = "primary" if name is None else name.lower()

        if name == "haplotig":
            name = "haplotigs"

        draft_asm_file = draft_yaml.decontaminated_file_path(
            draft_yaml.get_path(name), name
        )

        before = GfaStats(draft_asm_file).run()
        after = GfaStats(asm_file).run()

        asm_root = re.sub(r"\.fa(\.gz)?$", "", asm_file.name)

        gfa_out_file = asm_file.parent / f"{asm_root}.gfastats"
        gfa_io = get_output_filehandle(gfa_out_file, clobber)
        gfa_io.write(before.short_stats_string())
        gfa_io.write("\n")
        gfa_io.write(after.short_stats_string())
        gfa_io.close()

        vgp_out_file = asm_file.parent / f"{asm_root}.gather_vgp_stats"
        vgp_stats = VgpStats()
        vgp_stats.load_before_stats(before)
        vgp_stats.load_after_stats(after)
        vgp_io = get_output_filehandle(vgp_out_file, clobber)
        vgp_io.write(str(vgp_stats))
        vgp_io.close()


def write_chr_report_csv(
    out_template: Path,
    stats: AssemblyStats,
    out_assemblies: AssemblySet,
    clobber: bool,
):
    """
    Writes a `.chr_report.csv` file reporting on chromosome sequence lengths
    for all the haplotypes curated.  It also shows each sequences PretextView
    scaffold name alongside its chromosome sequence name generated by
    `pretext-to-asm`.
    """
    csv = stats.chromosomes_report_csv(out_assemblies)
    if not csv:
        return
    csv_file = out_template.with_name(out_template.name + ".chr_report.csv")
    with get_output_filehandle(csv_file, clobber) as csv_fh:
        csv_fh.write(csv)


def write_chr_csv_files(
    out_dir: Path,
    stats: AssemblyStats,
    out_assemblies: AssemblySet,
    clobber: bool,
    gz_flag: bool,
):
    """
    Writes (optionally gzip-compressed) `.chromosome.list.csv` files, required
    for our submissions to the ENA.  These CSV files do not contain a header!
    """
    gz = ".gz" if gz_flag else ""
    for asm in out_assemblies.values():
        if not asm.curated:
            continue
        if chr_names := stats.chromosome_name_csv(asm):
            csv_file = out_dir / f"{asm.name}.chromosome.list.csv{gz}"
            with get_output_filehandle(csv_file, clobber) as csv_fh:
                if gz:
                    csv_fh.write(chr_names.encode())
                else:
                    csv_fh.write(chr_names)


def write_sum_chrs(
    out_dir: Path,
    stats: AssemblyStats,
    out_assemblies: AssemblySet,
    clobber: bool,
):
    """
    Writes the `.sum_chrs` file for the main assembly in the set.
    """
    asm_key, asm = out_assemblies.main_assembly()
    report = stats.sum_chrs_report(asm_key, asm)
    sum_file = out_dir / f"{asm.name}.sum_chrs"
    with get_output_filehandle(sum_file, clobber) as sum_fh:
        sum_fh.write(report)


def write_info_yaml(
    out_template,
    stats: AssemblyStats,
    out_assemblies: AssemblySet,
    clobber,
):
    """
    Writes a `.info.yaml` file, which is used by the curators for reporting.
    """
    asm_stats = stats.per_assembly_stats
    info = {"assemblies": asm_stats}
    if len(asm_stats) > 1:
        info["manual_breaks"] = stats.breaks
        info["manual_joins"] = stats.joins

    haplotig_count = 0
    if h_asm := out_assemblies.get("Haplotig"):
        # Scaffolds read from the draft haplotigs file have rank == 0
        haplotig_count = len([x for x in h_asm.scaffolds if x.rank == 4])
    info["manual_haplotig_removals"] = haplotig_count
    info["percent_assembly_in_chromosomes"] = stats.percent_assembly_in_chromosomes
    info["interventions_per_gbp"] = stats.interventions_per_gbp

    yaml_file = out_template.with_name(out_template.name + ".info.yaml")
    with get_output_filehandle(yaml_file, clobber) as yaml_fh:
        yaml_fh.write(yaml.safe_dump(info, sort_keys=False))
